export const LOCAL_OBJECTS=[
{id:'sirius',name:'Sirius',nameZh:'天狼星',raHours:6.7525,decDeg:-16.7161,magnitude:-1.46,kind:'star',source:'local'},
{id:'canopus',name:'Canopus',nameZh:'老人星',raHours:6.3992,decDeg:-52.6957,magnitude:-.74,kind:'star',source:'local'},
{id:'arcturus',name:'Arcturus',nameZh:'大角星',raHours:14.261,decDeg:19.1824,magnitude:-.05,kind:'star',source:'local'},
{id:'vega',name:'Vega',nameZh:'織女星',raHours:18.6156,decDeg:38.7837,magnitude:.03,kind:'star',source:'local'},
{id:'capella',name:'Capella',nameZh:'五車二',raHours:5.2782,decDeg:45.998,magnitude:.08,kind:'star',source:'local'},
{id:'rigel',name:'Rigel',nameZh:'參宿七',raHours:5.2423,decDeg:-8.2016,magnitude:.13,kind:'star',source:'local'},
{id:'procyon',name:'Procyon',nameZh:'南河三',raHours:7.655,decDeg:5.225,magnitude:.34,kind:'star',source:'local'},
{id:'betelgeuse',name:'Betelgeuse',nameZh:'參宿四',raHours:5.9195,decDeg:7.4071,magnitude:.42,kind:'star',source:'local'},
{id:'altair',name:'Altair',nameZh:'牛郎星',raHours:19.8464,decDeg:8.8683,magnitude:.76,kind:'star',source:'local'},
{id:'aldebaran',name:'Aldebaran',nameZh:'畢宿五',raHours:4.5987,decDeg:16.5093,magnitude:.85,kind:'star',source:'local'},
{id:'antares',name:'Antares',nameZh:'心宿二',raHours:16.4901,decDeg:-26.432,magnitude:.96,kind:'star',source:'local'},
{id:'spica',name:'Spica',nameZh:'角宿一',raHours:13.4199,decDeg:-11.1613,magnitude:.98,kind:'star',source:'local'},
{id:'pollux',name:'Pollux',nameZh:'北河三',raHours:7.7553,decDeg:28.0262,magnitude:1.14,kind:'star',source:'local'},
{id:'fomalhaut',name:'Fomalhaut',nameZh:'北落師門',raHours:22.9608,decDeg:-29.6222,magnitude:1.16,kind:'star',source:'local'},
{id:'deneb',name:'Deneb',nameZh:'天津四',raHours:20.6905,decDeg:45.2803,magnitude:1.25,kind:'star',source:'local'},
{id:'regulus',name:'Regulus',nameZh:'軒轅十四',raHours:10.1395,decDeg:11.9672,magnitude:1.35,kind:'star',source:'local'},
{id:'castor',name:'Castor',nameZh:'北河二',raHours:7.5767,decDeg:31.8883,magnitude:1.58,kind:'star',source:'local'},
{id:'bellatrix',name:'Bellatrix',nameZh:'參宿五',raHours:5.4189,decDeg:6.3497,magnitude:1.64,kind:'star',source:'local'},
{id:'alnilam',name:'Alnilam',nameZh:'參宿二',raHours:5.6036,decDeg:-1.2019,magnitude:1.69,kind:'star',source:'local'},
{id:'alnitak',name:'Alnitak',nameZh:'參宿一',raHours:5.6793,decDeg:-1.9426,magnitude:1.74,kind:'star',source:'local'},
{id:'alioth',name:'Alioth',nameZh:'玉衡',raHours:12.9005,decDeg:55.9598,magnitude:1.76,kind:'star',source:'local'},
{id:'dubhe',name:'Dubhe',nameZh:'天樞',raHours:11.0621,decDeg:61.7508,magnitude:1.79,kind:'star',source:'local'},
{id:'alkaid',name:'Alkaid',nameZh:'搖光',raHours:13.7923,decDeg:49.3133,magnitude:1.86,kind:'star',source:'local'},
{id:'shaula',name:'Shaula',nameZh:'尾宿八',raHours:17.5601,decDeg:-37.1038,magnitude:1.62,kind:'star',source:'local'},
{id:'sargas',name:'Sargas',nameZh:'尾宿五',raHours:17.6219,decDeg:-42.9978,magnitude:1.86,kind:'star',source:'local'},
{id:'saiph',name:'Saiph',nameZh:'參宿六',raHours:5.7959,decDeg:-9.6696,magnitude:2.06,kind:'star',source:'local'},
{id:'mizar',name:'Mizar',nameZh:'開陽',raHours:13.3987,decDeg:54.9254,magnitude:2.23,kind:'star',source:'local'},
{id:'schedar',name:'Schedar',nameZh:'王良四',raHours:.6751,decDeg:56.5373,magnitude:2.24,kind:'star',source:'local'},
{id:'caph',name:'Caph',nameZh:'王良一',raHours:.1529,decDeg:59.1498,magnitude:2.27,kind:'star',source:'local'},
{id:'dschubba',name:'Dschubba',nameZh:'房宿三',raHours:16.0056,decDeg:-22.6217,magnitude:2.29,kind:'star',source:'local'},
{id:'merak',name:'Merak',nameZh:'天璇',raHours:11.0307,decDeg:56.3824,magnitude:2.37,kind:'star',source:'local'},
{id:'phecda',name:'Phecda',nameZh:'天璣',raHours:11.8972,decDeg:53.6948,magnitude:2.44,kind:'star',source:'local'},
{id:'gamma-cas',name:'Gamma Cassiopeiae',nameZh:'策',raHours:.9451,decDeg:60.7167,magnitude:2.47,kind:'star',source:'local'},
{id:'lesath',name:'Lesath',nameZh:'尾宿九',raHours:17.5127,decDeg:-37.2958,magnitude:2.7,kind:'star',source:'local'},
{id:'ruchbah',name:'Ruchbah',nameZh:'閣道三',raHours:1.4303,decDeg:60.2353,magnitude:2.68,kind:'star',source:'local'},
{id:'megrez',name:'Megrez',nameZh:'天權',raHours:12.2571,decDeg:57.0326,magnitude:3.31,kind:'star',source:'local'},
{id:'segin',name:'Segin',nameZh:'閣道二',raHours:1.9066,decDeg:63.6701,magnitude:3.35,kind:'star',source:'local'},
{id:'m31',name:'Andromeda Galaxy M31',nameZh:'仙女座星系',raHours:.7123,decDeg:41.2692,magnitude:3.44,kind:'galaxy',source:'local'},
{id:'m42',name:'Orion Nebula M42',nameZh:'獵戶座大星雲',raHours:5.5881,decDeg:-5.3911,magnitude:4,kind:'nebula',source:'local'},
{id:'m45',name:'Pleiades M45',nameZh:'昴宿星團',raHours:3.79,decDeg:24.1167,magnitude:1.6,kind:'cluster',source:'local'},
{id:'m13',name:'Hercules Cluster M13',nameZh:'武仙座球狀星團',raHours:16.6949,decDeg:36.4613,magnitude:5.8,kind:'cluster',source:'local'},
{id:'m57',name:'Ring Nebula M57',nameZh:'環狀星雲',raHours:18.8931,decDeg:33.0289,magnitude:8.8,kind:'nebula',source:'local'},
{id:'m51',name:'Whirlpool Galaxy M51',nameZh:'渦狀星系',raHours:13.4979,decDeg:47.1952,magnitude:8.4,kind:'galaxy',source:'local'},
{id:'m8',name:'Lagoon Nebula M8',nameZh:'礁湖星雲',raHours:18.0633,decDeg:-24.3867,magnitude:6,kind:'nebula',source:'local'}
];
export const CONSTELLATION_LINES=[
{constellation:'獵戶座',from:'betelgeuse',to:'bellatrix'},{constellation:'獵戶座',from:'betelgeuse',to:'alnitak'},{constellation:'獵戶座',from:'bellatrix',to:'alnilam'},{constellation:'獵戶座',from:'alnitak',to:'alnilam'},{constellation:'獵戶座',from:'alnilam',to:'saiph'},{constellation:'獵戶座',from:'alnilam',to:'rigel'},{constellation:'獵戶座',from:'saiph',to:'rigel'},
{constellation:'北斗七星',from:'dubhe',to:'merak'},{constellation:'北斗七星',from:'merak',to:'phecda'},{constellation:'北斗七星',from:'phecda',to:'megrez'},{constellation:'北斗七星',from:'megrez',to:'dubhe'},{constellation:'北斗七星',from:'megrez',to:'alioth'},{constellation:'北斗七星',from:'alioth',to:'mizar'},{constellation:'北斗七星',from:'mizar',to:'alkaid'},
{constellation:'仙后座',from:'caph',to:'schedar'},{constellation:'仙后座',from:'schedar',to:'gamma-cas'},{constellation:'仙后座',from:'gamma-cas',to:'ruchbah'},{constellation:'仙后座',from:'ruchbah',to:'segin'},
{constellation:'天蠍座',from:'dschubba',to:'antares'},{constellation:'天蠍座',from:'antares',to:'sargas'},{constellation:'天蠍座',from:'sargas',to:'shaula'},{constellation:'天蠍座',from:'shaula',to:'lesath'}
];
export const OBJECT_BY_ID=new Map(LOCAL_OBJECTS.map(o=>[o.id,o]));
